version: '3.8'

services:
  web:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: sh -c "
      echo 'Waiting for database...' &&
      until mysqladmin ping -h db --silent; do
        sleep 2
        echo 'Waiting for MySQL to be ready...'
      done &&
      echo 'Database is ready! Running migrations...' &&
      python manage.py migrate contenttypes --fake-initial &&
      python manage.py migrate auth --fake-initial &&
      python manage.py migrate accounts --fake-initial &&
      python manage.py migrate admin --fake-initial &&
      python manage.py migrate sessions --fake-initial &&
      python manage.py migrate --fake-initial &&
      echo 'Collecting static files...' &&
      python manage.py collectstatic --noinput &&
      echo 'Starting Gunicorn...' &&
      gunicorn festival.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    expose:
      - 8000
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: mysql
    expose:
      - 3306
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/mysql  # ✅ dbdata 볼륨 유지

  nginx:
    container_name: nginx
    build: ./config/nginx
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    ports:
      - "80:80"
    depends_on:
      - web
    environment:
      TZ: "Asia/Seoul"

# ✅ 데이터베이스, 정적/미디어 파일 저장을 위한 볼륨
volumes:
  static:
  media:
  dbdata:
