version: '3.8'

services:
  web:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: sh /home/app/web/config/docker/entrypoint.prod.sh
    env_file:
      - .env
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    expose:
      - 8000
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: mysql
    expose:
      - 3306
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/mysql

  nginx:
    container_name: nginx
    build: ./config/nginx
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    ports:
      - "80:80"
    depends_on:
      - web
    environment:
      TZ: "Asia/Seoul"

volumes:
  static:
  media:
  dbdata:
