version: '3.8'

services:
  # Django 웹 애플리케이션을 실행
  web:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile.prod  # Dockerfile.prod를 사용해 이미지를 빌드
    command: sh /home/app/web/config/docker/entrypoint.prod.sh  # entrypoint 스크립트 실행
    environment:
      DJANGO_SETTINGS_MODULE: festival.settings.prod
    env_file:
      - .env  # 환경 변수를 .env 파일에서 로드
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    expose:
      - 8000
    depends_on:
      - db

  # 데이터베이스 컨테이너 (MySQL)
  db:
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: mysql
    expose:
      - 3306
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/mysql

  # Nginx를 사용하여 웹 서버를 설정, Django 애플리케이션에 대한 요청을 처리
  nginx:
    container_name: nginx
    build: ./config/nginx
    volumes:
      - static:/home/app/web/static  # Nginx가 정적 파일을 제공할 수 있도록 설정
      - media:/home/app/web
