# Generated by Django 5.1.6 on 2025-02-23 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thumbnail', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('음식', '음식'), ('굿즈', '굿즈'), ('댄스', '댄스'), ('밴드', '밴드')], max_length=10)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('is_opened', models.BooleanField(default=True)),
                ('is_show', models.BooleanField(default=False)),
                ('scrap_count', models.IntegerField(default=0)),
                ('location', models.CharField(choices=[('교육관', '교육관'), ('대강당', '대강당'), ('신세계관', '신세계관'), ('생활관', '생활관'), ('정문', '정문'), ('포스코관', '포스코관'), ('학문관', '학문관'), ('휴웃길', '휴웃길'), ('학관', '학관'), ('학문관무대', '학문관무대'), ('스포츠트랙', '스포츠트랙')], max_length=10)),
                ('booth_num', models.IntegerField()),
                ('code', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.TextField(blank=True)),
                ('name', models.CharField(max_length=18)),
                ('price', models.IntegerField()),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_sale', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='booths.booth')),
            ],
        ),
        migrations.CreateModel(
            name='OperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('수요일', '수요일'), ('목요일', '목요일'), ('금요일', '금요일')], max_length=5)),
                ('date', models.IntegerField(choices=[(10, 10), (11, 11), (12, 12)])),
                ('open_time', models.CharField(max_length=5)),
                ('close_time', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='booths.booth')),
            ],
        ),
    ]
