# Generated by Django 5.1.6 on 2025-02-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='code',
            field=models.CharField(choices=[('1234', '1234'), ('4567', '4567'), ('7890', '7890'), ('0123', '0123')], max_length=50, unique=True),
        ),
    ]
