# Generated by Django 5.1.7 on 2025-04-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='booth_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='menu_thumbnails/'),
        ),
    ]
