# Generated by Django 5.1.6 on 2025-03-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='menu_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booth',
            name='notice_count',
            field=models.IntegerField(default=0),
        ),
    ]
