# Generated by Django 4.2.19 on 2025-02-19 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('수요일', '수요일'), ('목요일', '목요일'), ('금요일', '금요일')], max_length=5)),
                ('date', models.IntegerField(choices=[(10, 10), (11, 11), (12, 12)])),
                ('open_time', models.CharField(max_length=5)),
                ('close_time', models.CharField(max_length=5)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='booths.booth')),
            ],
        ),
    ]
