# Generated by Django 5.2 on 2025-05-04 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booth',
            old_name='is_committee',
            new_name='is_committe',
        ),
    ]
