# Generated by Django 4.2.19 on 2025-05-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0002_alter_booth_thumbnail_alter_menu_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='thumbnail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='thumbnail',
            field=models.TextField(blank=True),
        ),
    ]
