# Generated by Django 5.1.6 on 2025-02-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0002_alter_booth_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
