# Generated by Django 5.2 on 2025-05-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0002_rename_is_committee_booth_is_committe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='location',
            field=models.CharField(choices=[('교육관', '교육관'), ('대강당', '대강당'), ('신세계관', '신세계관'), ('생활관', '생활관'), ('정문', '정문'), ('포스코관', '포스코관'), ('학문관', '학문관'), ('휴웃길', '휴웃길'), ('학관', '학관'), ('학문관무대', '학문관무대'), ('스포츠트랙', '스포츠트랙'), ('잔디광장', '잔디광장'), ('아산공학관관', '아산공학관관'), ('스포츠트랙 옆', '스포츠트랙 옆'), ('학문관 4층 전시실', '학문관 4층 전시실'), ('정문 돌담 앞', '정문 돌담 앞'), ('학교 전체', '학교 전체'), ('ECC B4 삼성홀 앞', 'ECC B4 삼성홀 앞'), ('정문03', '정문03'), ('정문02', '정문02')], max_length=150),
        ),
    ]
