# Generated by Django 5.2 on 2025-05-04 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0003_alter_booth_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booth',
            old_name='is_committe',
            new_name='is_committee',
        ),
    ]
