# Generated by Django 5.1.6 on 2025-02-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0003_alter_booth_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatinghours',
            name='date',
            field=models.IntegerField(choices=[(14, 14), (15, 15), (16, 16)]),
        ),
    ]
