# Generated by Django 5.2 on 2025-05-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0004_rename_is_committe_booth_is_committee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='booth_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
