# Generated by Django 5.2 on 2025-05-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0006_alter_booth_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booth',
            name='is_committee',
        ),
    ]
