# Generated by Django 5.2 on 2025-05-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0007_remove_booth_is_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='is_committee',
            field=models.BooleanField(default=False),
        ),
    ]
