# Generated by Django 4.2.19 on 2025-05-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0009_alter_booth_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='category',
            field=models.CharField(choices=[('음식', '음식'), ('굿즈', '굿즈'), ('체험형', '체험형'), ('댄스', '댄스'), ('밴드', '밴드'), ('보컬', '보컬'), ('연극', '연극')], max_length=10),
        ),
    ]
