# Generated by Django 5.2 on 2025-05-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0011_alter_booth_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='category',
            field=models.CharField(choices=[('음식', '음식'), ('굿즈', '굿즈'), ('체험형', '체험형'), ('댄스', '댄스'), ('밴드', '밴드'), ('연극', '연극'), ('보컬', '보컬')], max_length=10, null=True),
        ),
    ]
