# Generated by Django 5.2 on 2025-05-04 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeBooth',
            fields=[
                ('booth_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booths.booth')),
                ('type', models.CharField(choices=[('기획', '기획'), ('대외협력', '대외협력'), ('홍보디자인', '홍보디자인'), ('프로모션', '프로모션')], max_length=10)),
            ],
            bases=('booths.booth',),
        ),
    ]
