# Generated by Django 5.1.6 on 2025-02-25 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
        ('shows', '0004_rename_performanceschedule_operatinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guestbook_notice', to='shows.show'),
        ),
    ]
