# Generated by Django 4.2.19 on 2025-02-27 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guestbook_booth', to='booths.booth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guestbook_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
