# Generated by Django 4.2.19 on 2025-02-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        #('accounts', '0002_remove_user_nickname'),
        ('accounts', '0001_initial'),  # 기존 0002_remove_user_nickname 대신 0001_initial을 참조

    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
