# Generated by Django 5.1.6 on 2025-02-25 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
        ('shows', '0003_alter_show_code_alter_show_show_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='performance_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shows.performanceschedule'),
        ),
    ]
