# Generated by Django 4.2.19 on 2025-05-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationnotice',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
