# Generated by Django 4.2.19 on 2025-02-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_notice_contact_info_notice_operating_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('운영중', '운영중'), ('운영종료', '운영종료')], default='running', max_length=20),
        ),
    ]
