# Generated by Django 5.1.6 on 2025-02-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_notice_performance_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='performance_schedule',
        ),
    ]
