# Generated by Django 4.2.19 on 2025-02-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_alter_notice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('운영중', '운영중'), ('운영종료', '운영종료')], default='운영중', max_length=20),
        ),
    ]
