# Generated by Django 5.1.6 on 2025-02-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceschedule',
            name='date',
            field=models.IntegerField(choices=[(10, 10), (11, 11), (12, 12)], default=10),
            preserve_default=False,
        ),
    ]
