# Generated by Django 4.2.19 on 2025-02-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='code',
            field=models.CharField(default='DEFAULT_CODE', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='show',
            name='is_opened',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='show',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='show',
            name='show_num',
            field=models.IntegerField(null=True),
        ),
    ]
