# Generated by Django 5.1.6 on 2025-02-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='name',
            new_name='title',
        ),
    ]
