# Generated by Django 5.1.6 on 2025-02-26 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_rename_name_show_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatinghours',
            old_name='end_time',
            new_name='close_time',
        ),
        migrations.RenameField(
            model_name='operatinghours',
            old_name='start_time',
            new_name='open_time',
        ),
        migrations.AlterField(
            model_name='operatinghours',
            name='date',
            field=models.IntegerField(choices=[(14, 14), (15, 15), (16, 16)]),
        ),
        migrations.AlterField(
            model_name='operatinghours',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='shows.show'),
        ),
    ]
