# Generated by Django 5.1.6 on 2025-02-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_performanceschedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_num',
            field=models.IntegerField(),
        ),
    ]
