# Generated by Django 5.1.6 on 2025-02-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_alter_show_code_alter_show_show_num'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerformanceSchedule',
            new_name='OperatingHours',
        ),
    ]
