# Generated by Django 5.1.6 on 2025-02-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_searchhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
