# Generated by Django 4.2.19 on 2025-02-20 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booths', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap_booth', to='booths.booth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
