# Generated by Django 5.1.6 on 2025-02-22 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0001_initial'),
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='booth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraps', to='booths.booth'),
        ),
    ]
