# Generated by Django 5.1.6 on 2025-05-03 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
